import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _ky = {
    'settings':           'Жөндөөлөр',
    'language':           'Тил',
    'notifications':      'Билдирмелер',
    'dark_mode':          'Күңүрт режим',
    'profile':            'Профил',
    'cache':              'Кэшти тазалоо',
    'support':            'Колдоо',
    'terms':              'Эрежелер',
    'home':               'Башкы',
    'cart':               'Себет',
    'favorites':          'Тандамалар',
    'chat':               'Чат',
    'shop':               'Дүкөн',
    'search':             'Издөө',
    'search_hint':        'Товар издеңиз...',
    'save':               'Сактоо',
    'cancel':             'Жокко чыгаруу',
    'delete':             'Өчүрүү',
    'yes':                'Ооба',
    'no':                 'Жок',
    'loading':            'Жүктөлүүдө...',
    'error':              'Ката кетти',
    'success':            'Ийгиликтүү',
    'ok':                 'Жарайт',
    'back':               'Артка',
    'close':              'Жабуу',
    'sign_out':           'Чыгуу',
    'product':            'Товар',
    'price':              'Баасы',
    'add_to_cart':        'Себетке кошуу',
    'in_cart':            'Себетте бар',
    'buy_now':            'Азыр сатып алуу',
    'description':        'Сүрөттөмө',
    'sizes':              'Размерлер',
    'colors':             'Түстөр',
    'characteristics':    'Характеристикалар',
    'similar':            'Окшош товарлар',
    'no_products':        'Табылган жок',
    'search_empty':       'Башка сөз менен издеп көрүңүз',
    'popular':            '🔥 Таанымал',
    'newest':             '🆕 Жаңы товарлар',
    'refresh':            'Жаңылоо',
    'filter':             'Чыпкалоо',
    'filter_reset':       'Тазалоо',
    'nearby':             'Мага жакын',
    'nearby_error':       'Жайгашкан жериңизди аныктоо мүмкүн болбоду. Геолокацияга уруксат бериңиз.',
    'nearby_count':       'жакын товар',
    'results':            'натыйжа',
    'camera_search':      'Издөө камерасы',
    'camera_soon':        'Жакында кошулат! 🚀\nТовардын сүрөтүн тартып издей аласыз.',
    'seller':             'Сатуучу',
    'container':          'Жайгашкан жери',
    'work_hours':         'Иш убактысы',
    'route':              'Маршрут түзүү',
    'write_seller':       'Сатуучуга жазуу',
    'select_size':        'Размер тандаңыз',
    'add_review':         'Пикир жазуу',
    'reviews':            'Пикирлер',
    'no_reviews':         'Азырынча пикир жок',
    'share':              'Бөлүшүү',
    'cart_empty':         'Себет бош',
    'cart_empty_desc':    'Товарларды себетке кошуңуз',
    'total':              'Жалпы',
    'checkout':           'Заказ берүү',
    'quantity':           'Саны',
    'favorites_empty':    'Тандамалар бош',
    'favorites_empty_desc':'Жаккан товарларды ♥ басып кошуңуз',
    'welcome_title':      'Дордойдун онлайн базары',
    'sign_in_google':     'Google менен кирүү',
    'sign_in_terms':      'Кирүү менен Колдонуу шарттарына\nкелишесиз',
    'cache_cleared':      'Кэш тазаланды ✅',
    'cache_error':        'Ката',
    'no_chats':           'Чаттар жок',
    'type_message':       'Билдирүү жазыңыз...',
    'send':               'Жиберүү',
    'seller_title':       'Сатуучу',
    'login':              'Кирүү',
    'register':           'Катталуу',
    'shop_title':         'Дүкөнүңүздү башкарыңыз!',
    'shop_desc':          'DD Online аркылуу товарларыңызды\nДордой базарынан дүйнөгө сатыңыз',
    'add_product':        'Товар кошуу',
    'my_products':        'Менин товарларым',
    'no_size':            'Размерсиз',
    'open':               'Ачык',
    'closed':             'Жабык',
    'no_info':            'Маалымат жок',
    'in_stock':           'Запаста бар',
    'out_of_stock':       'Запаста жок',
    'pcs':                'дана',
    'location_denied':    '📍 Уруксат бериңиз',
    'location_unknown':   'Сатуучунун картадагы жери белгисиз',
    'seller_no_info':     'Сатуучу маалыматы жок!',
    'chat_login_required':'Чат үчүн кирүү керек!',
    'own_product':        'Бул сиздин өз товарыңыз!',
    '2gis_not_installed': '2ГИС орнотулган жок',
    '2gis_download_hint': 'Маршрут үчүн 2ГИС тиркемесин жүктөп алыңыз.',
    'download':           'Жүктөп алуу',
    'nav_step1':          'Төмөндөгү баскычты басыңыз',
    'nav_step2':          '2ГИС тиркемеси ачылат',
    'nav_step3':          '"Маршрут түзүү" баскычын басып жолго чыгыңыз',
    'open_2gis':          '2ГИС менен маршрут түзүү',
    'login_error':         'Кирүүдө ката кетти',
    'seller_login':        'Сатуучу катары кирүү',
    'email_not_found':     'Почта тиркемеси табылбады',
    'messages':            'Билдирүүлөр',
    'selected':            'тандалды',
    'delete_chat':         'Чатты өчүрүү',
    'delete_chat_confirm': 'чатты өчүрөсүзбү?',
    'select_all':          'Баарын тандоо',
    'deselect_all':        'Баарын алып салуу',
    'new_chat':            'Жаңы чат',
    'cart_clear_title':    'Себетти тазалоо',
    'cart_clear_confirm':  'Бардык товарларды өчүрөсүзбү?',
    'back_to_products':    'Товарларга кайт',
    'size_label':          'Размер',
    'items_count':         'Товарлар саны:',
    'total_price':         'Жалпы баасы:',
    'order_placed':        'Буйрутма берилди!',
    'order_placed_desc':   'Сиздин буйрутмаңыз кабыл алынды! Сатуучу менен чат аркылуу байланышыңыз.',
    'great':               'Жакшы!',
  };

  static const _ru = {
    'settings':           'Настройки',
    'language':           'Язык',
    'notifications':      'Уведомления',
    'dark_mode':          'Тёмный режим',
    'profile':            'Профиль',
    'cache':              'Очистить кэш',
    'support':            'Поддержка',
    'terms':              'Правила',
    'home':               'Главная',
    'cart':               'Корзина',
    'favorites':          'Избранное',
    'chat':               'Чат',
    'shop':               'Магазин',
    'search':             'Поиск',
    'search_hint':        'Поиск товаров...',
    'save':               'Сохранить',
    'cancel':             'Отмена',
    'delete':             'Удалить',
    'yes':                'Да',
    'no':                 'Нет',
    'loading':            'Загрузка...',
    'error':              'Ошибка',
    'success':            'Успешно',
    'ok':                 'Хорошо',
    'back':               'Назад',
    'close':              'Закрыть',
    'sign_out':           'Выйти',
    'product':            'Товар',
    'price':              'Цена',
    'add_to_cart':        'В корзину',
    'in_cart':            'В корзине',
    'buy_now':            'Купить сейчас',
    'description':        'Описание',
    'sizes':              'Размеры',
    'colors':             'Цвета',
    'characteristics':    'Характеристики',
    'similar':            'Похожие товары',
    'no_products':        'Не найдено',
    'search_empty':       'Попробуйте другой запрос',
    'popular':            '🔥 Популярное',
    'newest':             '🆕 Новые товары',
    'refresh':            'Обновить',
    'filter':             'Фильтр',
    'filter_reset':       'Сбросить',
    'nearby':             'Рядом со мной',
    'nearby_error':       'Не удалось определить местоположение. Разрешите геолокацию.',
    'nearby_count':       'товаров рядом',
    'results':            'результатов',
    'camera_search':      'Поиск по фото',
    'camera_soon':        'Скоро! 🚀\nИщите товары по фотографии.',
    'seller':             'Продавец',
    'container':          'Местонахождение',
    'work_hours':         'Время работы',
    'route':              'Построить маршрут',
    'write_seller':       'Написать продавцу',
    'select_size':        'Выберите размер',
    'add_review':         'Написать отзыв',
    'reviews':            'Отзывы',
    'no_reviews':         'Отзывов пока нет',
    'share':              'Поделиться',
    'cart_empty':         'Корзина пуста',
    'cart_empty_desc':    'Добавьте товары в корзину',
    'total':              'Итого',
    'checkout':           'Оформить заказ',
    'quantity':           'Количество',
    'favorites_empty':    'Избранное пусто',
    'favorites_empty_desc':'Нажмите ♥ чтобы добавить товар',
    'welcome_title':      'Онлайн базар Дордоя',
    'sign_in_google':     'Войти через Google',
    'sign_in_terms':      'Войдя, вы соглашаетесь с\nусловиями использования',
    'cache_cleared':      'Кэш очищен ✅',
    'cache_error':        'Ошибка',
    'no_chats':           'Нет чатов',
    'type_message':       'Напишите сообщение...',
    'send':               'Отправить',
    'seller_title':       'Продавец',
    'login':              'Войти',
    'register':           'Зарегистрироваться',
    'shop_title':         'Управляйте своим магазином!',
    'shop_desc':          'Продавайте товары с Дордоя\nчерез DD Online по всему миру',
    'add_product':        'Добавить товар',
    'my_products':        'Мои товары',
    'no_size':            'Без размера',
    'open':               'Открыто',
    'closed':             'Закрыто',
    'no_info':            'Нет информации',
    'in_stock':           'В наличии',
    'out_of_stock':       'Нет в наличии',
    'pcs':                'шт',
    'location_denied':    '📍 Разрешите геолокацию',
    'location_unknown':   'Местоположение продавца неизвестно',
    'seller_no_info':     'Нет данных о продавце!',
    'chat_login_required':'Войдите для чата!',
    'own_product':        'Это ваш собственный товар!',
    '2gis_not_installed': '2ГИС не установлен',
    '2gis_download_hint': 'Скачайте приложение 2ГИС для построения маршрута.',
    'download':           'Скачать',
    'nav_step1':          'Нажмите кнопку ниже',
    'nav_step2':          'Откроется приложение 2ГИС',
    'nav_step3':          'Нажмите "Построить маршрут" и отправляйтесь',
    'open_2gis':          'Маршрут через 2ГИС',
    'login_error':         'Ошибка при входе',
    'seller_login':        'Войти как продавец',
    'email_not_found':     'Почтовое приложение не найдено',
    'messages':            'Сообщения',
    'selected':            'выбрано',
    'delete_chat':         'Удалить чат',
    'delete_chat_confirm': 'чат(а) будут удалены?',
    'select_all':          'Выбрать все',
    'deselect_all':        'Снять выбор',
    'new_chat':            'Новый чат',
    'cart_clear_title':    'Очистить корзину',
    'cart_clear_confirm':  'Удалить все товары?',
    'back_to_products':    'Вернуться к товарам',
    'size_label':          'Размер',
    'items_count':         'Количество товаров:',
    'total_price':         'Итого:',
    'order_placed':        'Заказ оформлен!',
    'order_placed_desc':   'Ваш заказ принят! Свяжитесь с продавцом через чат.',
    'great':               'Отлично!',
  };

  String get(String key) {
    final map = locale.languageCode == 'ru' ? _ru : _ky;
    return map[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ky', 'ru'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(_) => false;
}
